### ISSUE TITLE
Suggests for the list

### ISSUE THREAD

**Issue by mattcam** [ttntm/awesome-sfmc#2]
Started this SFMC awesome list back in 2017, feel welcome to make suggestions with a pull request.

**Comment by ttntm** [comment]
Hi @mattcam, thanks for the pointer - I suppose you are referring to this repository: https://github.com/sfmcdg/awesome-salesforce-marketingcloud - correct?

Having had a better look at it, I feel tempted to simply merge my little list into yours. Would that be welcome on your side, or do you feel that my list's content and/or parts of it would not be a good fit for your project?

**Comment by mattcam** [comment]
Feel very welcome to merge so that we can contribute together, or to keep the list that you are maintaining separate. Regardless feel welcome to make a PR to add your awesome list to https://github.com/sfmcdg/awesome-salesforce-marketingcloud
